### ISSUE TITLE
Robomongo authentification failed on service run

### ISSUE THREAD

**Issue by billouboq** [Studio3T/robomongo#1183]
Hi,

I'm using mongodb **3.2.7** with **WiredTiger** and authentification on **centOS 7**.
I don't know why but if I run my mondb with "`mongod --auth`" or just "`mongod`" I can connect to my mongodb server from an other computer, using robomongo. But if I stop mongod and run mongodb service "`service mongod start`" suddenly I can't connect anymore. 

> "Cannot connect to the MongoDB at 127.0.0.1:52410. Authentication failed"

here is my mongod config file: 

```
# mongod.conf
# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

# Where and how to store data.
storage:
  dbPath: /var/lib/mongo
  journal:
    enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:

# how the process runs
processManagement:
  fork: true  # fork and run in background
  pidFilePath: /var/run/mongodb/mongod.pid  # location of pidfile

# network interfaces
net:
  port: 27017
# bindIp: 127.0.0.1  # Listen to local interface only, comment to listen on all interfaces.

#security:
security:
  authorization: enabled
```
